#!/bin/bash                                                                                                                                                                    
cp -R -u [[:upper:]]* /tmp/u

