#!/bin/bash                                                                                                                                                                 cpcp -R -u [[:upper:]]* /tmp/u

